# Generated by Django 4.1.7 on 2023-03-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name': 'Abilities', 'verbose_name_plural': 'Abilities'},
        ),
        migrations.AddField(
            model_name='ability',
            name='name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
