# Generated by Django 4.1.7 on 2023-03-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ability_options_ability_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
