# Generated by Django 4.1.7 on 2023-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_app_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='picture',
            field=models.ImageField(upload_to='media/img/'),
        ),
    ]
