# Generated by Django 4.1.7 on 2023-04-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='file',
            field=models.FileField(upload_to='media/pdf'),
        ),
    ]
