# Generated by Django 4.1.7 on 2023-04-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_pdfupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoAmIPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/img')),
            ],
        ),
    ]
